# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\HPz420\Documents\GitHub\LB-RPPSOC\RPPSOC-Blink1.cydsn\RPPSOC-Blink1.cyprj
# Date: Sun, 08 Sep 2019 23:12:42 GMT
#set_units -time ns
create_clock -name {Clock_1(routed)} -period 135.63919972872159 -waveform {0 67.8195998643608} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {Clock_2(routed)} -period 165.78124411288195 -waveform {0 82.890622056441} [list [get_pins {ClockBlock/dclk_1}]]
create_clock -name {CyXTAL_32kHz} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/clk_32k_xtal}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyPLL_OUT} -period 15.071022192080177 -waveform {0 7.53551109604009} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 15.071022192080177 -waveform {0 7.53551109604009} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 9 19} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 11 23} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]


# Component constraints for C:\Users\HPz420\Documents\GitHub\LB-RPPSOC\RPPSOC-Blink1.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\HPz420\Documents\GitHub\LB-RPPSOC\RPPSOC-Blink1.cydsn\RPPSOC-Blink1.cyprj
# Date: Sun, 08 Sep 2019 23:12:37 GMT
