/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPI.h"
#include "SPI_SPI_UART.h"
#include "SPI_PINS.h"
#include "SPI_SPI_UART_PVT.h"
#include "SPI_PVT.h"
#include "SPI_BOOT.h"
#include "Output_Pin_0.h"
#include "Output_Pin_0_aliases.h"
#include "Output_Pin_1.h"
#include "Output_Pin_1_aliases.h"
#include "Input_Pin_0.h"
#include "Input_Pin_0_aliases.h"
#include "Input_Pin_1.h"
#include "Input_Pin_1_aliases.h"
#include "Input_0_Int.h"
#include "Input_1_Int.h"
#include "SPI_SCBCLK.h"
#include "SPI_ss_s.h"
#include "SPI_ss_s_aliases.h"
#include "SPI_miso_s.h"
#include "SPI_miso_s_aliases.h"
#include "SPI_sclk_s.h"
#include "SPI_sclk_s_aliases.h"
#include "SPI_mosi_s.h"
#include "SPI_mosi_s_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

